# Generated by Django 4.2.2 on 2023-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gilam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('size', models.IntegerField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='new', max_length=20)),
                ('adress', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=100)),
                ('sum', models.IntegerField(max_length=500)),
            ],
        ),
    ]
