# Generated by Django 4.2.2 on 2023-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_gilam_size_remove_gilam_sum_gilam_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gilam',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gilam',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
