# Generated by Django 4.2.2 on 2023-07-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gilam_size_gilam_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gilam',
            old_name='size',
            new_name='olcham',
        ),
    ]
